# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Genezzo-Contrib-Clustered
version:      0.06
version_from: lib/Genezzo/Contrib/Clustered/Clustered.pm
installdirs:  site
requires:
    FreezeThaw:                    0.0
    Genezzo::GenDBI:               0.45

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
